### ISSUE TITLE
Can not open links

### ISSUE THREAD

**Issue by InlineWebb** [needle-and-thread/birdie#187]
Can not open links, regardless of the default browser. Copying works.
Reinstalling app did not help.

[https://drive.google.com/open?id=0BwYBEi_Xt23QQkFEVC1GRjFUcG8](url)

**Comment by nathandyer** [comment]
@Providex Did you build Birdie from source, or did you install it from a PPA? If so, which one? As far as I know, this has been fixed in our repo for a few months now.

**Comment by WebShapedBiz** [comment]
@nathandyer Can you please clarify what do you mean by "our repo"? The "Birdie Stable" Launchpad repo was updated in February 2014 by old maintainers and "Birdie Daily" in February 2016 so without the May 29 commit fixing link open issue.
Is there a third repo that I'm unaware of?

Cheers.

**Comment by z0rc** [comment]
Are we dead yet?

**Comment by nathandyer** [comment]
This is fixed in master, so I'm going to go ahead and close this. The PPAs are no longer maintained and will be going away soon, as AppCenter is the new method for downloading and updating Birdie.
